image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Initalise terraform
    init: |
      export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
      export AWS_SECRET_ACCESS_KEY="$AWS_SECRETS_ACCESS_KEY"
      export AWS_DEFAULT_REGION="eu-west-1"
    command: |
      terraform init
      terraform plan

vscode:
  extensions:
    - hashicorp.terraform
